export const TYPEOFMOVEMENT = {
    INGRESO: { NAME: 'INGRESO', CODE: 'I' },
    EGRESO: { NAME: 'EGRESO', CODE: 'E' }
}

export const TYPEOFMOVEMENTARRAY = [
    TYPEOFMOVEMENT.INGRESO,
    TYPEOFMOVEMENT.EGRESO
]