version: '3'
services:
  #PHP Service
  angular:
    build:
      context: .
      dockerfile: dockerfile.prod
    container_name: angular
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - astoria-network

  #Nginx Service
  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - astoria-network

#Docker Networks
networks:
  astoria-network:
    driver: bridge
